version: 2

multi-ecosystem-groups:
  application-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Sao_Paulo

updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: master
    patterns:
      - "*"
    multi-ecosystem-group: application-dependencies
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(deps)

  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    patterns:
      - "*"
    multi-ecosystem-group: application-dependencies
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci(deps)

  - package-ecosystem: docker
    directories:
      - /
      - /src/CorporateServiceDesk.Api
    target-branch: master
    patterns:
      - "*"
    multi-ecosystem-group: application-dependencies
    open-pull-requests-limit: 5
    commit-message:
      prefix: build(docker)
