services:
  corporateservicedesk.api:
    image: ${DOCKER_REGISTRY-}corporateservicedeskapi
    build:
      context: .
      dockerfile: src/CorporateServiceDesk.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"